### ISSUE TITLE
Cleaning

### ISSUE THREAD

**Issue by LaurentLienhard** [HowIAutomatedThis/HIATModuleTemplate#3]
Remove the module previously compiled in order to be able to launch a new compilation on a healthy basis

**Comment by gaelcolas** [comment]
that is critical, but only locally.
On a CI server, it should be a clean environment every time.
FTR, ModuleBuilder has a `clean` option if you use it.

**Comment by HowIAutomatedThis** [comment]
Indeed it is a question of doing it just on my development environment
